"""empty message

Revision ID: 127c3e6bdc26
Revises: 29e5839436af
Create Date: 2020-10-26 18:14:10.792731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127c3e6bdc26'
down_revision = '29e5839436af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordlist', schema=None) as batch_op:
        batch_op.drop_index('ix_wordlist_title')
        batch_op.create_index(batch_op.f('ix_wordlist_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wordlist_title'))
        batch_op.create_index('ix_wordlist_title', ['title'], unique=1)

    # ### end Alembic commands ###
