"""empty message

Revision ID: 15c68dd20043
Revises: 5e94c69b101d
Create Date: 2020-10-26 18:08:11.621009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c68dd20043'
down_revision = '5e94c69b101d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordlist', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_wordlist_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wordlist_title'))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
