"""added words model

Revision ID: 4636cc7634f5
Revises: a079d1d99fcd
Create Date: 2020-10-18 20:55:51.739840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4636cc7634f5'
down_revision = 'a079d1d99fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('part', sa.String(length=64), nullable=True),
    sa.Column('definition', sa.String(length=128), nullable=True),
    sa.Column('wordlist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wordlist_id'], ['wordlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    # ### end Alembic commands ###
