"""empty message

Revision ID: 5e1bff7b7318
Revises: 924bf46b366b
Create Date: 2020-10-26 17:57:08.963196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1bff7b7318'
down_revision = '924bf46b366b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wordlist', 'title',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.create_index(op.f('ix_wordlist_title'), 'wordlist', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wordlist_title'), table_name='wordlist')
    op.alter_column('wordlist', 'title',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
