"""empty message

Revision ID: 5fc0bd6657ce
Revises: 68c10d3f9240
Create Date: 2020-10-25 23:08:12.411404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc0bd6657ce'
down_revision = '68c10d3f9240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_word_name'), 'word', ['name'], unique=True)
    op.create_unique_constraint(None, 'word', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'word', type_='unique')
    op.drop_index(op.f('ix_word_name'), table_name='word')
    # ### end Alembic commands ###
