"""empty message

Revision ID: 68c10d3f9240
Revises: 4636cc7634f5
Create Date: 2020-10-20 00:46:54.478869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c10d3f9240'
down_revision = '4636cc7634f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wordlists_words',
    sa.Column('wordlist_id', sa.Integer(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.ForeignKeyConstraint(['wordlist_id'], ['wordlist.id'], )
    )
    op.drop_constraint(None, 'word', type_='foreignkey')
    op.drop_column('word', 'wordlist_id')
    op.create_index(op.f('ix_wordlist_title'), 'wordlist', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wordlist_title'), table_name='wordlist')
    op.add_column('word', sa.Column('wordlist_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'word', 'wordlist', ['wordlist_id'], ['id'])
    op.drop_table('wordlists_words')
    # ### end Alembic commands ###
