"""empty message

Revision ID: 924bf46b366b
Revises: a232d974601c
Create Date: 2020-10-26 17:48:47.785951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924bf46b366b'
down_revision = 'a232d974601c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wordlist_title', table_name='wordlist')
    op.create_index(op.f('ix_wordlist_title'), 'wordlist', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wordlist_title'), table_name='wordlist')
    op.create_index('ix_wordlist_title', 'wordlist', ['title'], unique=False)
    # ### end Alembic commands ###
