"""empty message

Revision ID: 9fc2932157fc
Revises: 5fc0bd6657ce
Create Date: 2020-10-26 17:41:28.286028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc2932157fc'
down_revision = '5fc0bd6657ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_word_name'), 'word', ['name'], unique=False)
    op.drop_index('ix_wordlist_title', table_name='wordlist')
    op.create_index(op.f('ix_wordlist_title'), 'wordlist', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wordlist_title'), table_name='wordlist')
    op.create_index('ix_wordlist_title', 'wordlist', ['title'], unique=1)
    op.drop_index(op.f('ix_word_name'), table_name='word')
    # ### end Alembic commands ###
