"""empty message

Revision ID: a232d974601c
Revises: a684ca7b99bc
Create Date: 2020-10-26 17:47:55.567025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a232d974601c'
down_revision = 'a684ca7b99bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_word_name'), 'word', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_name'), table_name='word')
    # ### end Alembic commands ###
