"""empty message

Revision ID: a684ca7b99bc
Revises: 9fc2932157fc
Create Date: 2020-10-26 17:46:53.921987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a684ca7b99bc'
down_revision = '9fc2932157fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_word_name', table_name='word')
    op.create_index(op.f('ix_word_name'), 'word', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_name'), table_name='word')
    op.create_index('ix_word_name', 'word', ['name'], unique=False)
    # ### end Alembic commands ###
