"""empty message

Revision ID: e24d1d691744
Revises: 5543414c3528
Create Date: 2020-10-27 15:04:53.517147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24d1d691744'
down_revision = '5543414c3528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_column('example2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example2', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
